apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: frontend-route
  namespace: dev
spec:
  parentRefs:
    - name: fanvault-gateway
      namespace: kgateway-system
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: dev-frontend
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: user-route
  namespace: dev
spec:
  parentRefs:
    - name: fanvault-gateway
      namespace: kgateway-system
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/users
      backendRefs:
        - name: dev-user-service
          port: 3001
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: commerce-route
  namespace: dev
spec:
  parentRefs:
    - name: fanvault-gateway
      namespace: kgateway-system
  rules:
    # 1. Admin Commerce operations
    - matches:
        - path:
            type: PathPrefix
            value: /api/commerce/admin
      backendRefs:
        - name: dev-commerce-service
          port: 3002

    # 2. General Commerce operations
    - matches:
        - path:
            type: PathPrefix
            value: /api/commerce
      backendRefs:
        - name: dev-commerce-service
          port: 3002
