apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Fanvault-CloudOps/Fanvault-GitOps.git
    targetRevision: HEAD
    path: gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
