replicaCount: 2

image:
  pullPolicy: IfNotPresent

hpa:
  minReplicas: 2
  maxReplicas: 5

config:
  ENVIRONMENT: "production"
  USE_SECRETS_MANAGER: "true"
  SECRET_ID: "fanvault-prod-app-secrets"
  AI_PROVIDER: "openai"
  S3_PRODUCT_IMAGES_BUCKET: "fanvault-prod-product-images-773384830607"

# image.repository and image.tag are updated automatically by CI/CD on each deploy
image:
  repository: ""
  tag: ""

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::773384830607:role/fanvault-ai-irsa-role"
