replicaCount: 1
hpa:
  maxReplicas: 2
config:
  NODE_ENV: "development"
  USE_SECRETS_MANAGER: "false"
  COGNITO_REGION: "us-east-1"
  COGNITO_USER_POOL_ID: "us-east-1_O7cQQXD1P"
  COGNITO_CLIENT_ID: "3fioa78u18rkf7c3kiqb3sud55"

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::773384830607:role/fanvault-user-irsa-role"
image:
  repository: 773384830607.dkr.ecr.us-east-1.amazonaws.com/fanvault-dev-user-service
  tag: sha-initial
