replicaCount: 1

hpa:
  maxReplicas: 2

config:
  NODE_ENV: "development"
  USE_SECRETS_MANAGER: "false"
  COGNITO_REGION: "us-east-1"
  COGNITO_USER_POOL_ID: "us-east-1_VsEibvEp2"
  COGNITO_CLIENT_ID: "7p64vafrf82fo5pp9q7cn8v0c2"
